<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Ice Belt',
                'category' => 'Men\'s Clothing',
                'description' => 'Premium leather belt with ice buckle design. Perfect for formal and casual wear.',
                'brand' => 'Fashion Forward',
                'sku' => 'ICEBELT-MCL-001',
                'quantity' => 13,
                'cost_price' => 1000.00,
                'selling_price' => 1500.00,
                'discount_price' => null,
                'low_stock_threshold' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Classic White T-Shirt',
                'category' => 'Men\'s Clothing',
                'description' => '100% cotton classic fit t-shirt. Essential wardrobe staple.',
                'brand' => 'Basic Wear',
                'sku' => 'WHITET-MCL-002',
                'quantity' => 25,
                'cost_price' => 500.00,
                'selling_price' => 800.00,
                'discount_price' => 650.00,
                'low_stock_threshold' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Denim Jeans',
                'category' => 'Men\'s Clothing',
                'description' => 'Comfortable straight-leg denim jeans. Available in multiple washes.',
                'brand' => 'Denim Co.',
                'sku' => 'DENIM-MCL-003',
                'quantity' => 18,
                'cost_price' => 1200.00,
                'selling_price' => 1800.00,
                'discount_price' => null,
                'low_stock_threshold' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Summer Dress',
                'category' => 'Women\'s Clothing',
                'description' => 'Lightweight floral summer dress. Perfect for warm weather occasions.',
                'brand' => 'Summer Style',
                'sku' => 'SUMMER-WCL-004',
                'quantity' => 12,
                'cost_price' => 800.00,
                'selling_price' => 1200.00,
                'discount_price' => 950.00,
                'low_stock_threshold' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Bluetooth Headphones',
                'category' => 'Electronics',
                'description' => 'Wireless noise-cancelling headphones with premium sound quality.',
                'brand' => 'SoundTech',
                'sku' => 'BLUETOOTH-ELC-005',
                'quantity' => 8,
                'cost_price' => 2500.00,
                'selling_price' => 3500.00,
                'discount_price' => null,
                'low_stock_threshold' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Smart Watch',
                'category' => 'Electronics',
                'description' => 'Feature-rich smartwatch with health monitoring and GPS.',
                'brand' => 'TechWear',
                'sku' => 'SMARTWATCH-ELC-006',
                'quantity' => 5,
                'cost_price' => 4000.00,
                'selling_price' => 6000.00,
                'discount_price' => 5000.00,
                'low_stock_threshold' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Running Shoes',
                'category' => 'Footwear',
                'description' => 'Lightweight running shoes with superior cushioning and support.',
                'brand' => 'RunFast',
                'sku' => 'RUNSHOES-FTW-007',
                'quantity' => 15,
                'cost_price' => 1800.00,
                'selling_price' => 2800.00,
                'discount_price' => null,
                'low_stock_threshold' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Casual Sneakers',
                'category' => 'Footwear',
                'description' => 'Versatile casual sneakers for everyday comfort and style.',
                'brand' => 'StreetStyle',
                'sku' => 'CASUALSNEAKERS-FTW-008',
                'quantity' => 22,
                'cost_price' => 900.00,
                'selling_price' => 1400.00,
                'discount_price' => 1100.00,
                'low_stock_threshold' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Leather Wallet',
                'category' => 'Accessories',
                'description' => 'Genuine leather wallet with multiple card slots and coin pocket.',
                'brand' => 'LeatherCraft',
                'sku' => 'LEATHERWALLET-ACC-009',
                'quantity' => 30,
                'cost_price' => 600.00,
                'selling_price' => 900.00,
                'discount_price' => null,
                'low_stock_threshold' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'Sunglasses',
                'category' => 'Accessories',
                'description' => 'Stylish sunglasses with UV protection and polarized lenses.',
                'brand' => 'SunShade',
                'sku' => 'SUNGLASSES-ACC-010',
                'quantity' => 16,
                'cost_price' => 700.00,
                'selling_price' => 1100.00,
                'discount_price' => 850.00,
                'low_stock_threshold' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Backpack',
                'category' => 'Bags',
                'description' => 'Durable backpack with laptop compartment and multiple pockets.',
                'brand' => 'TravelGear',
                'sku' => 'BACKPACK-BAG-011',
                'quantity' => 11,
                'cost_price' => 1000.00,
                'selling_price' => 1600.00,
                'discount_price' => null,
                'low_stock_threshold' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Handbag',
                'category' => 'Bags',
                'description' => 'Elegant handbag perfect for work and evening events.',
                'brand' => 'Elegance',
                'sku' => 'HANDBAG-BAG-012',
                'quantity' => 9,
                'cost_price' => 1500.00,
                'selling_price' => 2200.00,
                'discount_price' => 1800.00,
                'low_stock_threshold' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Perfume',
                'category' => 'Beauty',
                'description' => 'Luxury fragrance with long-lasting scent and elegant packaging.',
                'brand' => 'Luxury Scents',
                'sku' => 'PERFUME-BTY-013',
                'quantity' => 7,
                'cost_price' => 2000.00,
                'selling_price' => 3200.00,
                'discount_price' => null,
                'low_stock_threshold' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Skincare Set',
                'category' => 'Beauty',
                'description' => 'Complete skincare routine set with cleanser, toner, and moisturizer.',
                'brand' => 'SkinCare Plus',
                'sku' => 'SKINCARE-BTY-014',
                'quantity' => 14,
                'cost_price' => 1200.00,
                'selling_price' => 1900.00,
                'discount_price' => 1500.00,
                'low_stock_threshold' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Kitchen Knife Set',
                'category' => 'Home & Garden',
                'description' => 'Professional-grade kitchen knife set with wooden block storage.',
                'brand' => 'Chef\'s Choice',
                'sku' => 'KNIFESET-HG-015',
                'quantity' => 6,
                'cost_price' => 3000.00,
                'selling_price' => 4500.00,
                'discount_price' => null,
                'low_stock_threshold' => 2,
                'is_active' => true,
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }

        $this->command->info('Products seeded successfully!');
    }
}
